project_id = "nduhgptimbvmlswyfpxn"

[functions.analyze-image]
verify_jwt = true

[functions.generate-prompt]
verify_jwt = true

[functions.enhance-prompt]
verify_jwt = true

[functions.deep-analyze-image]
verify_jwt = true

[functions.generate-variations]
verify_jwt = true